version: '3'

tasks:
  docker-test:
    cmds:
      - docker build --rm -t go-experiments/tcpclose .
      - >
        container_id=$(docker run -d go-experiments/tcpclose)
        && docker wait $container_id
        && docker logs $container_id
        && docker cp "$container_id:/workspace/dump.cap" dump.cap
        && docker rm $container_id